# Generated by Django 4.0.6 on 2022-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='num_rows',
            field=models.IntegerField(),
        ),
    ]
